### ISSUE TITLE
Include license

### ISSUE THREAD

**Issue by jonathanspw** [beanbaginc/kgb#10]
Can you please include the license file in the repo, preferably as `LICENSE` or `COPYING`?  This will make the package more compatible with OS packaging.

**Comment by chipx86** [comment]
This is in the repository now, but it didn't make the release. Feel free to backport that. The license in use is defined in `setup.py`.

**Comment by jonathanspw** [comment]
Thanks!  Can you add it to the pypi build as well?

**Comment by chipx86** [comment]
Can do. Just released 7.1.1 with the LICENSE file.
