### ISSUE TITLE
Python 3.11 compatibility

### ISSUE THREAD

**Issue by jonathanspw** [beanbaginc/kgb#9]
It would be great if things were updated for Python 3.11 compatibility.  Currently pytest has a lot of failures in 3.11.

**Comment by chipx86** [comment]
We're planning on 3.11 support. We've been waiting for 3.11 to get closer to release, but it's probably a reasonable time to start on it.

**Comment by jonathanspw** [comment]
Makes sense.  This is currently a blocker preventing me in packaging kgb in the official Fedora repositories.

**Comment by chipx86** [comment]
I'm investigating it now. We'll see what all is required. Currently I'm being highly successful in segfaulting Python, which is always a good time.

**Comment by jonathanspw** [comment]
Well if it gives you any motivation I'm building/adding this as a dependency of pydiffx...as a dependency of RBTools.

**Comment by chipx86** [comment]
I appreciate your work on this!

Making good progress on 3.11. If I can get some of the issues figured out, we'll have a release very shortly.

**Comment by chipx86** [comment]
There were some internal changes in Python 3.11 with how functions are set up and invoked, but I believe I've figured out all the issues. Should have a kgb 7.1 release out within the next day or two.

**Comment by chipx86** [comment]
Thanks for your patience. There were a lot of changes under-the-hood in Python that we had to work around and test.

We just released kgb 7.1, featuring Python 3.11 support: https://pypi.org/project/kgb/

**Comment by jonathanspw** [comment]
Great!  I've got a workable build for Fedora rawhide and I'm pushing it through the package review process.

**Comment by chipx86** [comment]
Thank you for your work on this! Closing this one out.
